name: Informe de error (es)
description: Reportar un error para ayudarnos a mejorar
title: "[Error] "
labels: ["kind/bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar un error. Por favor, completa el siguiente formulario para ayudarnos a entender y reproducir el problema.
  - type: textarea
    id: description
    attributes:
      label: Descripción del error
      description: Una descripción clara y concisa de cuál es el error.
      placeholder: Describe el error aquí...
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Pasos para reproducir
      description: Pasos para reproducir el comportamiento.
      placeholder: |
        1. Ejecutar '...'
        2. Ver error '...'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamiento esperado
      description: Una descripción clara y concisa de lo que esperabas que sucediera.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Comportamiento actual
      description: Una descripción clara y concisa de lo que realmente sucedió.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Versión de minikube
      description: Ejecuta `minikube version` y pega la salida aquí.
      placeholder: minikube version v...
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Información del entorno
      description: Ejecuta `minikube logs` y pega la salida aquí, o proporciona información relevante del entorno.
      placeholder: |
        Sistema operativo:
        Controlador:
        Versión de Kubernetes:
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Contexto adicional
      description: Agrega cualquier otro contexto sobre el problema aquí, como capturas de pantalla o registros.
    validations:
      required: false
